if: "(type IN (pull_request, cron, api)) OR (tag IS present)"
language: node_js
node_js:
- stable
install:
- yarn
script: yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
- yarn start
deploy:
  provider: npm
  email: r.diener@wikom.de
  skip_cleanup: true
  api_key:
    secure: DPWpRgfFE+rX9w3H80EI4aFvE/Ndj56DYXZ9f7Vw89dN7GuHf3STs0gLItC9MfKIfMyNNL0EifuUMwIjDbrYJY24PMGU1N8TmeQYJKOYztesQd2g8OTjUTIsRw5g/jF93mGlpMhjqzXNFScRMy3VsLTJl2RKlRNZT6oC4lvYQ8MXQVJp4lK+WYFV/POV/NNopPcUpbEx3K2Pde7afWE/L9qid+JsyjD/HLxHNQ6XsFT/fyyQedcApn0SwAi8KH1NAuk1mVaplFcDmyq1Tri5m18R2RX/bBYDgxjgQgOSbSDNhpyQ8W68tCfudIhZ93QiK5I/4NKMmvCK9ula0lNGFDlQmENxA6kwFGbtdZq+oIGWhMkLezQR4BLBgAtRl/XG6xHH8u6tERULk2JSulnFxs7dTuu5s4iKk4h/TqyCiBrT4YXaR6ZNw5eXrnB6vtMVBOfxWi4mZqivYuiEhiCk84RzY/iP65eckxRRU4KDIEql6cgfWhhGrEAAlSx24soW4Hpbd6Pk1QsWxuSNNpfzuFU6RX+sWaJmAYweuUHCpfnag/RNTUZblU3pw30bnrw+FnBqdQLPHMsgg56YIbADOI9Bch7gJJTcVxryiaXZfemrmbNiiryFOlve8uBOGHqWU5LYKJob+likcKpQF1VAs0Bu6yKPcoC+zlTrRcBaxaI=
  on:
    tags: true
    all_branches: true
notifications:
  slack:
    rooms:
      secure: T3SY42AraSacQy2Xh6yHe8IYcmnF2kjBMkslbQQBOKb4KKJhFsLliierXIJurQZi4CKyk+X6Xc2KdHSorgTV3HS+Ku7JU42p5V7Dv+dBZj9GxWSDiq+ORM1baXVWqMcO+RKbFGZeZFc4/+zUcY0CEJUneGj+xEkEH0zlcEiZ7IOeDw0nurtL9bW4piztyAHKhrYStETaioMxjIkKMFN5eTDVFuUDLNjE2bO/JRlNJVhOcm57isxlco/lr/hPlKPBGYaM73LJw/dQgGLyt9ucgzTZqI/tckJK8Xk5opz5jf8lCLVD0PfuHL2r5F1fejLvkCIv9uQIRPS6P2v9+2PTomcNm9mlNeShlym7Jc8oYjcDLCt0+YvxpsCs/DTVVQdNAEUD0+FjnMy7L2/ssbXlSKKtkeNud1mCu8KdkqRc6eEutZfR711wYqEnbcV03NEhvGdhzSwf+FtFBp6KxqpVW0UM2RdTMk1oSa1tOYgMtjAhNqozczW+gL66RHisi4PAcAD+nCsMqXy9TZcrO/O58rHPSt/Yybb69RvMleBUxxYPFyAuSCsjfCpRumbT43PIaOhETbRJ2RDdEB2+H/P2bLpKCzV7mqVGVEH3wbhvIcC9DpADde0Lwm/Mc7ejoM3VMVrtNbMIEvs9920NJIkLoKXpAM4fKYhXElNfUPKZwig=
