'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
/**
 * Created by rouven on 15.03.17.
 */

var PREFIX = '@@wikom-data/';

var LOAD_DATA_PENDING = exports.LOAD_DATA_PENDING = PREFIX + 'LOAD_DATA_PENDING';
var LOAD_DATA_SUCCESS = exports.LOAD_DATA_SUCCESS = PREFIX + 'LOAD_DATA_SUCCESS';
var LOAD_DATA_FAILURE = exports.LOAD_DATA_FAILURE = PREFIX + 'LOAD_DATA_FAILURE';
var LOAD_DATA_CANCEL = exports.LOAD_DATA_CANCEL = PREFIX + 'LOAD_DATA_CANCEL';
var LOAD_DATA_PROGRESS = exports.LOAD_DATA_PROGRESS = PREFIX + 'LOAD_DATA_PROGRESS';

var CLEAR_DATA = exports.CLEAR_DATA = PREFIX + 'CLEAR_DATA';
var REFRESH_DATA = exports.REFRESH_DATA = PREFIX + 'REFRESH_DATA';

var SET_PAGINATION = exports.SET_PAGINATION = PREFIX + 'SET_PAGINATION';
var CLEAR_PAGINATION = exports.CLEAR_PAGINATION = PREFIX + 'CLEAR_PAGINATION';

var SET_USER = exports.SET_USER = PREFIX + 'SET_USER';